highligher: pygments
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: pygments

collections:
  netmeetings:
    output: true
  workshops:
    output: true


future: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      
