highligher: pygments
markdown: kramdown
url: http://overturetool.org

collections:
  netmeetings:
    output: true
  workshops:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      
